Feature/kenji/front revise product
quest-academia/YunoCode pull request #10
Opened 2020-10-30 06:31 UTC by kenji-0612

お疲れ様です。

現在、【商品修正画面】の作成（レイアウト表示）を実装しているのですが、
ブラウザのアプリに上手く表示されずに悩んでいます。

分からないことが多すぎてなかなか上手くいきません。

・ルーツを記述する場所は今まで通りroutes/web.phpであっていますでしょか？
また記述内容はどのように記載するのが正解でしょうか？

・同様にコントローラーの記載場所も分からずに困っています。
この場合は新たに自分でファイルを作成し、そこにコードを書き込んでいく。ような流れになるのでしょうか？

・viewsのファイルも自分で作成しコードを書き込んでいってしまったのですが、これも間違い（ファイルの中身・コードは別として）だったでしょうか？（そもそもルーツ、コントローラーの記述が上手くいっていないのにviewsファイルを実装している次点でおかしな話しなんでしょうけど。。。）

新しいブランチ名をfeature/kenji/FrontReviseController（Revise＝修正、改訂という意味の為）として作業を再開したのですが、
FrontReviseControllerという名前のファイルが見つからなかったので、そもそも間違いだったのかな？とも思っているのですが、
その通りでしょうかね？

質問内容が分かりにくい上
また振り出しに戻るような内容の質問ばかりで申し訳ありません。

**まずは、ルーツ、コントローラーを正しく記述でき、ブラウザのアプリに【商品修正画面】を表示させるところまでを実装できたらなと考えています。**

その為にお忙しい中お手数ですが、ご確認と何かアドバイスを頂けると助かります。
よろしくお願いします。

2020-10-31 04:25 UTC, kenji-0612 commented
お忙し中回答ありがとうございます。

アドバイス頂いた通りにweb.phpにルーティングを追記しました。
（storeアクションの後にeditを追加したのみ）

その後の流れはFrontProductControllerに正しいメゾットを足していけば
ブラウザにアプリが表示されるという形で問題無いでしょうか？
それともweb.phpに別途ルーティング（Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');のような形のもの）を記述していく必要がありますでしょうか？

力不足で申し訳ありません。

ご確認よろしくお願いします。

2020-11-02 06:57 UTC, kenji-0612 commented
お疲れ様です。

現在行っている【商品修正画面】のレイアウト表示について２点ほどご質問をさせて頂きたいと思います。

１、http://192.168.33.11/products/{id}/editにアクセスをする場合｛id｝部分にはどういったidを入力するべきでしょうか？

２、http://192.168.33.11/products/{id}/editにアクセス（id部分が分からなかった為今回はユーザー名を入力）したところ
Undefined variable: dataとのエラー（return view('products.frontReviseProduct',$data);部分）が出てしまいました。
未定義変数のデータがあるという意味だと思うのですが、この場合はまだコードの記述が足りない。
（ $data=[

」;）のような$dataを定義する必要がある。という認識で問題ないでしょうか？

以上の２点のご確認とアドバイスよろしくお願いします。

2020-11-03 13:42 UTC, kenji-0612 commented
お疲れ様です。

【商品修正画面】のレイアウト表示を作成しました。

提出が遅くなってしまい申し訳ありません。

・コントローラーのeditアクションの実装コマンドは記述した内容であっていますでしょうか？
（現在は【http://192.168.33.11/products/1/edit】でアクセスすると【frontCreateProduct.blade.php】で作成したレイアウト画面が表示されます）

・画面定義書を参考に作成したのですが、【修正】・【修正】ボタンの配置（間隔）が上手くいきません。
もう少しお互いのボタンの間隔を広げるにはCSSにコードを追記？という方法もあるのかなと思うのですが、
この場合は【frontCreateProduct.blade.php】で実装するのが正しい方法でしょうか？

以上の２点とレイアウト表示、実装コマンドのご確認よろしくお願いします。

2020-11-07 02:19 UTC, kenji-0612 commented
お疲れ様です。

商品修正画面の画面表示（選択した商品の表示）が正しく実装できているかの課題についてなんですが、
自分なりにいろいろ調べたり、考えてコードを記述してみたのですが、なかなか表示できずにいます。

おそらくコントローラーに新たにコードを記述、その後viewに新たにコードを記述という流れだと思うのですが、まだコントローラーを少し変更したくらいです（それも間違っているコード）
一応間違えのコードもそのまま記述してあります。

なので上記の課題を実装するにあたってアドバイスをお願いしたいです。
（できればコードの説明？なども教えてもらえると凄く助かります。）

ボタンの間隔は定義書通りにスペースを作れました。

ご確認よろしくお願いします。

2020-11-07 08:42 UTC, kenji-0612 commented
商品一覧画面の値を修正画面に持ってくることができました。

商品画像を変更する場合はファイルを選択し画像を指定する流れだと思うのですが、
カテゴリーと受講生受付状態もその商品にあった選択肢が表示されていないとまだ完成とはいかないでしょうか？
（現在は「選択してください」が表示されている状態）

2020-11-08 10:01 UTC, kenji-0612 commented
・現在選択中の画像が表示されるように実装してみました。
【・商品画像】の下にメイン画像が表示されるようになりましたがこのような形で問題なかったでしょうか？

・商品カテゴリーと受講生受付状態をその選択肢が選択されているように
コードを追記したりしてみたのですが上手く表示されません。
主に{!! Form::text('title',$product->title,['class'=>'form-control ']) !!}のようなコードを記述して試してみました。

そこでいくつか質問があります。
・今回もタイトル名を表示させた時のように【{!! Form::text('title',$product->title,['class'=>'form-control ']) !!}】のようなコードを追記していくのが正解でしょうか？
それとも別のコードの記述もしくは現在書かれているコードの編集によって表示される流れでしょうか？

以上の点のご確認よろしくお願いします。

2020-11-09 13:41 UTC, kenji-0612 commented
サブ画像の表示を忘れていました。

しっかりと表示されるように実装しました。

ご確認よろしくお願いします。

2020-11-12 13:45 UTC, kenji-0612 commented
お疲れ様です。

【商品カテゴリー】と【受講生受付状態】欄にそれぞれ商品名と受付状態が表示されるように
実装してみました。

こ確認よろしくお願いします。

2020-11-15 16:08 UTC, kenji-0612 commented
お疲れ様です。

商品修正画面に商品カテゴリーと受講生受付状態の選択肢が正しく遷移されるように実装しました。

遅くなってしまい申し訳ありませんでした。

ご確認よろしくお願いします。

2020-11-15 22:21 UTC, quest-academia commented
確認しました！

OKです😊
コードも確認

2020-11-15 22:57 UTC, quest-academia requested changes
修正のほど、宜しくお願い致します🙇‍♂️

2020-11-18 15:37 UTC, kenji-0612 commented
お疲れ様です。

サブ画像が存在しない場合に『ファイルを選択』は残したままさらに画像なしの文字を表示するように
実装してみました。

ご確認よろしくお願いします。

2020-11-18 20:29 UTC, SekiYukihiro requested changes
確認しました！
とても良いですね、
こちらの内容で問題ないので、一旦ここまででマージしました😊

画像なしの場合も、左詰めで大丈夫です❗️
お疲れ様でした☺️

次は、storeアクションを見ながら、
バリデーションの実装を続けてやっていって下さい😊

ご不明点があれば、お聞きくださいね！

2020-11-18 20:29 UTC, merged