商品登録画面作成
quest-academia/YunoCode pull request #4
Opened 2020-09-01 02:39 UTC by mushajobs

お疲れ様です。
商品登録画面を作成しました。
ご確認お願いします。
gitのエラーで色々操作していたので、変な箇所があるかもしれません。何かエラーや修正しなければならないものが出てきたらば教えて頂けると有難いです。
よろしくお願いします。

2020-09-01 14:32 UTC, SekiYukihiro requested changes
確認しました！

自分の環境に落として見てみましたが、
きちんと保存処理が正常に実行され、かなり素晴らしいと思います！

複数テーブルに渡る複雑な内容にも関わらず、
ここまで良く作っていただいたと思います。

特に、バリデーションエラーが各入力項目の真下に表示されたり
バリデーションエラーを日本語化していたり、細かい部分に気が利いていて
すごいと思います。

いくつか、GitHub上で指摘を送りましたので、
そちらを訂正いただければと思います。

2020-09-01 14:32 UTC, SekiYukihiro commented on app/Http/Controllers/FrontCreateProductsController.php
> +        if($sub_image1 = $request->sub_image1){
if($sub_image1 = $request->sub_image1){
if文の中に＝を書くことはあまりないですし、
簡潔に、

if($request->sub_image1){

で良いと思います！

2020-09-01 14:32 UTC, SekiYukihiro commented on app/Http/Controllers/FrontCreateProductsController.php
> +        }
データベースに空文字が入るのもあまり良くないので、
else以降は不要だと思います。

そうなると、
Product::create([
という書き方は一気に登録できて楽なのですが
今回はあえて使わないでいきましょう。

$product->title = $request->title;

のように、
１つ１つ代入していく方法でいきましょう！

2020-09-01 14:32 UTC, SekiYukihiro commented on app/Http/Controllers/FrontCreateProductsController.php
> +            $subImage1Name = time().'.'.$sub_image1->getClientOriginalName();
オリジナルの名前を使わなくて良いと思います。

必要なのは、拡張子だけですかね。

確か、getExtension()みたいな形で拡張子だけ取得できるので
拡張子だけを持ってきましょう。

2020-09-01 14:32 UTC, SekiYukihiro commented on resources/lang/ja/validation.php
> +    'between'              => [
バリデーション日本語化できていて、すばらしいです！！

2020-09-01 14:32 UTC, SekiYukihiro commented on resources/views/products/frontCreateProduct.blade.php
> +                <div class="form-group @if(!empty($errors->first('title'))) has-error @endif">
エラーを各項目の真下に
出しているのも、最高ですね！！

2020-09-01 14:32 UTC, SekiYukihiro commented on database/migrations/2020_08_28_213233_create_products_table.php
> +            $table->string('overview');
これだと、ER図などの文字数制限の２５６文字まで
文字数を入れられなくないですか？
（他のカラムは、上限を超えたDB側の設定となっているのでまだ良いですが、
　可能であればDBとバリデーションの制限文字数を合わせましょう！）

2020-09-01 14:32 UTC, SekiYukihiro commented on resources/views/products/frontCreateProduct.blade.php
> +                            <p>円</p>
「円」は入力フォームの右側にくるようにしたいですね。

2020-09-01 14:32 UTC, SekiYukihiro commented on routes/web.php
> +    Route::resource('products', 'FrontCreateProductsController', ['only' => ['create', 'store']]);
FrontCreateProductsController
ですが、
CRUD処理すべてを担当するコントローラなので、シンプルに
FrontProductsController
で良いと思うのですが、いかがでしょうか？

違っていたら言ってください！

2020-09-01 14:32 UTC, SekiYukihiro commented on composer.lock
>  <<<<<<< HEAD
composer install　すると、
エラーが出て上手くできませんでした。

多分、ここにコンフリクトした際の残骸が残っていたせいだと
思います！

次から気をつけましょう＾＾

2020-09-01 15:33 UTC, mushajobs commented on app/Http/Controllers/FrontCreateProductsController.php
> +        if($main_image = $request->main_image){
たしかにその通りですね
main_imageに関してはバリデーションで必須項目になっているので必ず存在しますね

2020-09-01 15:37 UTC, mushajobs commented on app/Http/Controllers/FrontCreateProductsController.php
> +        if($sub_image1 = $request->sub_image1){
ありがとうございます
よくよく考えれば＝は普通書かないですね...

2020-09-01 15:43 UTC, mushajobs commented on app/Http/Controllers/FrontCreateProductsController.php
> +        }
かしこまりました！
ありがとうございます
今回の場合、Product::createの書き方だと何かエラーが起きやすかったり、避けたほうがいい理由があれば教えて頂きたいです！

2020-09-01 15:44 UTC, mushajobs commented on app/Http/Controllers/FrontCreateProductsController.php
> +            $subImage1Name = time().'.'.$sub_image1->getClientOriginalName();
名前は必要ないんですね
修正しておきます！

2020-09-01 15:51 UTC, mushajobs commented on composer.lock
>  <<<<<<< HEAD
すみませんでした
コンフリクトしたファイルは最後に再確認するようにします！

2020-09-01 16:09 UTC, mushajobs commented on routes/web.php
> +    Route::resource('products', 'FrontCreateProductsController', ['only' => ['create', 'store']]);
そのほうがいいと思います！
ありがとうございます

2020-09-01 16:34 UTC, mushajobs commented on database/migrations/2020_08_28_213233_create_products_table.php
> +            $table->string('overview');
LaravelQuestと同様にAppServiceProvider.phpに以下の一文を記入していました。
`public function boot()
    {
        \Schema::defaultStringLength(191);
    }`
これが原因で256文字保存できていませんでした。この部分を消してmigrateしなおしたらうまくいきました。

2020-09-01 16:39 UTC, mushajobs commented on resources/views/products/frontCreateProduct.blade.php
> +                            <p>円</p>
自分の画面ではフォームの右側に「円」が表示されています。
もしかしたらプッシュした際のデータが並んでいない時のデータだったかもしれないのでもう一度プッシュしますのでご確認お願いします。
それでも修正されていないようでしたら原因を考えたいと思います。

2020-09-01 16:58 UTC, mushajobs commented on app/Http/Controllers/FrontCreateProductsController.php
> +        ]);
教えて頂きありがとうございます！
実装できました！

2020-09-01 21:05 UTC, SekiYukihiro commented on app/Http/Controllers/FrontProductsController.php
> +
少しレベルの高い話ですが、
読みやすいように、
各コードのまとまりの上に、コメントを書くようにしてみていただけませんか？
ここだけでなく、全体的にやってみていただけると嬉しいです！

　　// メイン画像を指定のパスに保存する
        $mainImageName = time().'.'.$request->main_image->getClientOriginalExtension();
        $target_path = public_path('/productImage/');
        $request->main_image->move($target_path,$mainImageName);
        $product->main_image = $mainImageName;

　　// サブ画像１が存在すれば、サブ画像１を指定のパスに保存する
        if($request->sub_image1){
            $subImage1Name = time().'.'.$sub_image1->getClientOriginalExtension();
            $target_path = public_path('/image/');
            $sub_image1->move($target_path,$subImage1Name);
            $product->sub_image1 = $subImage1Name;
        }

2020-09-01 21:22 UTC, SekiYukihiro requested changes
おお、改善が早いですね！！
とても良くなったと思います😊

既にかなりお出来になるので
少しレベルが高めの話も含んでいますが、
いくつかアドバイスを追加しましたので、
改めてご確認いただけると幸いです！

お手数ですが、引き続き頑張ってみてください。
宜しくお願い致します！

2020-09-01 21:22 UTC, SekiYukihiro commented on app/Http/Requests/CreateProductRequest.php
> +
いいかんじですね！

2020-09-01 21:22 UTC, SekiYukihiro commented on resources/views/welcome.blade.php
>              </div>
円は入力フォームの右側にくるようになりましたね！

ただ、バリデーションエラーが走ると、こんな感じになるので、
こちらはなおしましょう！

<img width="317" alt="スクリーンショット 2020-09-02 5 59 23" src="https://user-images.githubusercontent.com/45893677/91906285-e95a6180-ece2-11ea-9142-d1c5bb663573.png">

2020-09-01 21:22 UTC, SekiYukihiro commented on resources/views/welcome.blade.php
>              </div>
あと、フッターがなぜが２重になっているのですが、なぜでしょうか、、、？
<img width="1037" alt="スクリーンショット 2020-09-02 5 58 55" src="https://user-images.githubusercontent.com/45893677/91906455-29b9df80-ece3-11ea-919c-3a21a7ab4878.png">

2020-09-01 21:22 UTC, SekiYukihiro commented on resources/views/products/frontCreateProduct.blade.php
> +                </div>
指摘していませんでしたが、
商品カテゴリーと、受講生受付状態も
バリデーションエラーが出た後に、「前回選択していた状態に戻す」ことができると
ベストですね！

少し難しいかもですが、やってみてください！

2020-09-01 21:22 UTC, SekiYukihiro commented on database/migrations/2020_08_28_213233_create_products_table.php
> +            $table->string('overview');
OKです！
ただ、データベースの種類によっては、２５５文字制限が掛かったりするので、
下記のように、それぞれのカラムで文字数制限を変えて
マイグレーションを書き直しましょう！

$table->string('name', 50)

2020-09-01 21:29 UTC, SekiYukihiro commented on app/Http/Controllers/FrontProductsController.php
> +
ちなみに、コメントは
Viewには書かなくてOKで、
コントローラとルーター辺りに書けばOKかなと思います。

2020-09-01 22:07 UTC, SekiYukihiro requested changes
コメントを追記しました！

2020-09-01 22:07 UTC, SekiYukihiro commented on app/Http/Controllers/FrontProductsController.php
> +        $target_path = public_path('/productImage/');
あと、こちらも指摘していませんでしたが、
変数はスネークケースで書くのではなく、キャメルケースで書くのが一般的ですかね。

既にキャメルケースで書かれている部分もあるので、
キャメルケースで統一しましょう！

->の後に来ている、プロパティはスネークケースのままでOKです！

2020-09-02 00:41 UTC, mushajobs commented on resources/views/welcome.blade.php
>              </div>
そこまで見れていませんでした...
ありがとうございます

2020-09-02 09:14 UTC, mushajobs commented on resources/views/products/frontCreateProduct.blade.php
> +                </div>
そのほうがいいですね！
変更しました！

2020-09-02 09:17 UTC, mushajobs commented on resources/views/welcome.blade.php
>              </div>
コードを見直してみましたが、原因が分かりません...
自分の画面では1重の表示になっています
もう一度プッシュしますので再度ご確認いただければと思います。

2020-09-02 09:19 UTC, mushajobs commented on app/Http/Controllers/FrontProductsController.php
> +        $target_path = public_path('/productImage/');
わかりました
キャメルケースで統一します！

2020-09-02 09:23 UTC, mushajobs commented on app/Http/Controllers/FrontProductsController.php
> +
了解しました
コメント追記します
今後はコメント書いていくようにします！

2020-09-02 09:54 UTC, mushajobs commented
developをプルしてコンフリクトも解消しました！
再度ご確認お願いします

2020-09-02 12:19 UTC, mushajobs commented on resources/views/welcome.blade.php
>              </div>
おそらくコンフリクトのせいでfooter.blade.phpに記述が2重になってしまったのだと思います。
すみません...
コンフリクト解消したので、これで大丈夫だと思います。
よろしくお願いします。

2020-09-02 13:11 UTC, SekiYukihiro approved these changes
とても、いいですね！
綺麗なコードにしていただいたと思います。

コメントなどは、これからも意識して分かりやすいコードをめざしていきましょう。

問題ありませんのでマージさせて頂きます！
宜しくお願い致します！

2020-09-02 13:12 UTC, merged