Feature/takano/front search product
quest-academia/YunoCode pull request #5
Opened 2020-09-07 15:40 UTC by mushajobs

お疲れ様です。
商品一覧画面が完成しました。
ご確認お願いします。
シーディングで商品データを一括で登録できます。
検索用に商品カテゴリーと受講生受付状態のすべての組み合わせを作成しています。
また、AND検索機能の確認として商品概要に「Laravel」「CakePHP」「Symphony」「LaravelとCakePHP」「CakePHPとSymphony」「LaravelとSymphony」と記述したデータがあるので検索機能の確認で使って頂けると有難いです。
商品名がLaravelQuest1、LaravelQuest2、LaravelQuest3、LaravelQuest4で「メイン画像だけのもの」、「サブ画像が1～3枚のもの」の4つのデータを作成しています。詳細画面で画像の配置を確認するときに見て頂ければと思います。
よろしく願い致します。

2020-09-08 14:07 UTC, SekiYukihiro commented on resources/views/products/frontShowProduct.blade.php
> +                    @endif
綺麗にできていると思うのですが、
こちらは、サブ画像が１枚〜２枚のとき、サブ画像が中心に寄るように作ってみましょう！

2020-09-08 14:11 UTC, SekiYukihiro commented on resources/views/products/frontIndexProduct.blade.php
> +                        </select>
見た目的に、設計通りに作っていただいているのですが、
少し見た目に違和感がありますね、、、！

設計と変わってしまいお手数なのですが
キーワード検索を中央に寄せるなり、
枠で囲って見た目を変えるなり、
一度、試してみていただけませんでしょうか？

2020-09-08 14:18 UTC, SekiYukihiro commented on app/Http/Controllers/SearchController.php
> +        $search3 = $request->input('overview');
変数名がわかりにくいので、
それぞれ、
$categorySearchId, $statusSearchId, $overviewSearchWord などで良いのでなおでしょうか？

2020-09-08 14:20 UTC, SekiYukihiro commented on app/Http/Controllers/SearchController.php
> +        $keywords = preg_split('/[\p{Z}\p{Cc}]++/u', $search3, -1, PREG_SPLIT_NO_EMPTY);
上記に伴い、こちらも$overviewKeywordsなどに変える。

2020-09-08 14:53 UTC, SekiYukihiro requested changes
遅くなりましたが、確認しました！

ここまで１人で考えて、よく実装されたと思います。
何より、コードがきちんとコメントが書けていて見やすいですね！
とてもレベルが高いと思います😊

細かい指摘なども多いのですが、いくつかGItHubにコメントを書かせて頂きました。
ご自分で考えていただく必要のある点もあり
大変かもですが、今一度ご確認お願いいたします！

また、詳細ページの設計書は問題ないと思います。

ご質問などあれば、お気軽にどうぞ！
宜しくお願い致します。

2020-09-08 14:53 UTC, SekiYukihiro commented on resources/views/products/frontIndexProduct.blade.php
> +        <div class="d-flex justify-content-center m-2">
ページネーションの上部にもう少し余白を空けましょう！

2020-09-08 14:53 UTC, SekiYukihiro commented on app/Http/Controllers/SearchController.php
> +
検索機能は、ほぼ完璧に近いのですが、
１点セキュリティ上の問題があります！

%や_などのワイルドカードと呼ばれる文字で検索すると、
全件のデータを取得できてしまいます。

これらの文字で検索された場合を想定して、エスケープ 処理を追加しましょう！

2020-09-08 14:53 UTC, SekiYukihiro commented on app/Http/Controllers/SearchController.php
> +class SearchController extends Controller
SearchControllerを作っていただいていますが、
（検索条件にカテゴリーなどを含んでいるといえど）
検索対象はProductsなので、Productsコントローラの中に
search（）メソッドを作る形の方がいいかと思うのですが、
いかがでしょうか？

2020-09-08 14:53 UTC, SekiYukihiro commented on app/Http/Controllers/FrontProductsController.php
> +        $product = Product::find($id);
showメソッド、綺麗に書けていると思うのですが、
$idが存在しない値で入力された場合、エラーになってしまいます。

idが想定外の数字でも、文字列を入力された場合でも
エラーにならないように考えて実装してみましょう！

2020-09-08 14:53 UTC, SekiYukihiro commented on app/Http/Controllers/SearchController.php
> +
検索結果表示の際に、検索したキーワードとカテゴリ&ステータスを
入力欄に残すようにしてみましょう！

2020-09-10 01:07 UTC, mushajobs commented on resources/views/products/frontShowProduct.blade.php
> +                    @endif
分かりました！
修正してみます

2020-09-10 01:24 UTC, mushajobs commented on resources/views/products/frontIndexProduct.blade.php
> +                        </select>
たしかに違和感はありますね...
左端に表示するように修正しました。
多少はよくなったと思いますが、気になる点があれば教えて頂けると有難いです。
よろしくお願いします。

2020-09-10 01:24 UTC, mushajobs commented on app/Http/Controllers/SearchController.php
> +        $search3 = $request->input('overview');
ありがとうございます
修正します！

2020-09-10 01:58 UTC, mushajobs commented on app/Http/Controllers/SearchController.php
> +class SearchController extends Controller
特に考えがあったわけではないので、Productsコントローラーにメソッドを作ります！

2020-09-10 16:03 UTC, mushajobs commented on app/Http/Controllers/SearchController.php
> +
ありがとうございます
色々調べてみたのですが、以下の関数を追記して実装しました。
もし、まだセキュリティ上の問題があればご指摘いただければと思います。
`public static function escapeLike($str) {
        return str_replace(['\\', '%', '_'], ['\\\\', '\%', '\_'], $str);
    }`
よろしくお願いします。

2020-09-11 04:49 UTC, mushajobs commented on app/Http/Controllers/FrontProductsController.php
> +        $product = Product::find($id);
実装できました！
showメソッドに以下の一文を加えています。
`if (is_null($product)) {
            abort(404);
        }`
ご確認お願いします。

2020-09-12 23:24 UTC, SekiYukihiro commented on resources/views/products/frontShowProduct.blade.php
>                      @endif
OKです！

とても綺麗に配置できています！
スマホサイズでも確認しましたが、完璧ですね😊

2020-09-12 23:25 UTC, SekiYukihiro commented on resources/views/products/frontShowProduct.blade.php
> +                    @endif
OKです！

非常に綺麗にできていると思います！
スマホサイズでも確認しましたが、完璧ですね😊

2020-09-12 23:26 UTC, SekiYukihiro commented on resources/views/products/frontIndexProduct.blade.php
> +                        </select>
左に寄せていただいて、かなり見た目が良くなったと思います😊

僕としてはこれでOKです。
あとは、ゆーやさんにもみていただきましょう！

2020-09-12 23:33 UTC, SekiYukihiro commented on resources/views/products/frontIndexProduct.blade.php
> +        <div class="d-flex justify-content-center m-2">
OKです！

2020-09-12 23:38 UTC, SekiYukihiro commented on app/Http/Controllers/FrontProductsController.php
> +        $product = Product::find($id);
完璧です！！

エラー表示画面も、
ご自分でカスタマイズされていて
素晴らしすぎます、、、！😊

2020-09-12 23:40 UTC, SekiYukihiro commented on app/Http/Controllers/SearchController.php
> +        $keywords = preg_split('/[\p{Z}\p{Cc}]++/u', $search3, -1, PREG_SPLIT_NO_EMPTY);
OKです！

2020-09-13 17:33 UTC, mushajobs commented on app/Http/Controllers/SearchController.php
> +
作成完了しました。
商品登録画面と同様の方法で実装しています。
ご確認お願いします。

2020-09-14 02:58 UTC, mushajobs commented on app/Http/Controllers/SearchController.php
> +
実装できました！
検索欄は右に配置しなおしてあります。
ご確認お願いします。

2020-09-14 14:05 UTC, SekiYukihiro requested changes
実際のアプリとコードともに、確認しました！
OKです😊

POSTメソッドに変更されて、URLもみやすくなったと思います！
キーワード保持もばっちりですね。

ただ、１点だけ、
スマホサイズの画面になったときに検索機能が画面の下の方に
移動するのが見づらいかなと思いました。

スマホサイズのときは、画面上部に検索機能を移動させていただくことは
可能でしょうか？
（前からこのような仕様だったら、指摘が遅くなりすみません！）

何度も修正お手数ですが、ご確認ください。

2020-09-14 21:15 UTC, merged