Feature/takano/front search product
quest-academia/YunoCode pull request #6
Opened 2020-09-27 12:17 UTC by mushajobs

お疲れ様です。
ご指摘いただいていた以下2点修正しました。
・&yen;等の特殊文字コードで検索したときの検索語の表示
・商品登録画面で「登録に失敗しました」のエラーメッセージの表示

お時間あるときにご確認お願いします。
よろしくお願いします。

2020-09-29 02:47 UTC, mushajobs commented
お疲れ様です
viewを作成してフラッシュメッセージを表示させました。
保存に成功すれば一覧画面に遷移するようにしています。
ご確認お願いします。

2020-10-02 23:34 UTC, quest-academia requested changes
遅くなりましたが、確認させていただきました！

登録に成功したら、一覧に飛んで成功メッセージが表示されるのは、とても良いと思います！
（モーダルまで作られて素晴らしいです:bangbang:）

ただ、失敗した時に、どこにも遷移しないため
エラーメッセージが表示されません。

.envファイルのDATABASE=のデータベース名を適当に書き換えてから
登録ボタンを押してエラーチェックをしてみましょう。
何も表示されないことになります。

失敗時の画面遷移先（return back()でもOK）を指定しましょう:blush:

2020-10-02 23:34 UTC, quest-academia commented on resources/views/commons/flash_message.blade.php
> +</div>
モーダルまで作られて、素晴らしいと思います！

ただ、ここ、インデントが少し変なので、インデントだけ直しましょう😊

2020-10-02 23:34 UTC, quest-academia commented on app/Http/Controllers/FrontProductsController.php
> +            session()->flash('flash_message', '登録が失敗しました');
遅くなりましたが、確認させていただきました！

登録に成功したら、一覧に飛んで成功メッセージが表示されるのは、とても良いと思います！

ただ、失敗した時に、どこにも遷移しないため
エラーメッセージが表示されません。

.envファイルのDATABASE=のデータベース名を適当に書き換えてから
登録ボタンを押してエラーチェックをしてみましょう。
何も表示されないことになります。

失敗時の画面遷移先（return back()でもOK）を指定しましょう。

2020-10-02 23:34 UTC, quest-academia commented on app/Http/Controllers/FrontProductsController.php
> +            return redirect('products/')->with('flash_message', '出品が完了しました');
登録に成功したら、一覧に飛んで成功メッセージが表示されるのは、とても良いと思います！

2020-10-03 15:51 UTC, mushajobs commented on resources/views/commons/flash_message.blade.php
> +</div>
ありがとうございます
修正しました！

2020-10-03 15:56 UTC, mushajobs commented on app/Http/Controllers/FrontProductsController.php
> +            session()->flash('flash_message', '登録が失敗しました');
ご確認ありがとうございます！
失敗時の戻り先について
return back()->with('flash_message', '登録が失敗しました');
という形で修正しています。
登録前にデータベース名を変更しているため、登録に失敗後、以下の画像のような画面になってしまいますが問題はないでしょうか？
https://gyazo.com/8e56fc164b997ef8f2cd13fdffd3e279
よろしくお願いします。

2020-10-06 14:49 UTC, SekiYukihiro commented
OKです！
問題ありませんので、マージさせていただきました:sparkles:
完璧です！！

ご確認、宜しくお願い致します！！

2020-10-06 14:49 UTC, merged