Feature/kenji/front login
quest-academia/YunoCode pull request #8
Opened 2020-10-04 05:48 UTC by kenji-0612

お疲れ様です。

言われた通り修正や追記をして見ました。

・【初めての方はこちらから】ボタンの背景色もより画面定義書に近い色に変更するために、ボタンの色（blue,redなど）やコードを['class' => 'btn btn-sm btn-info mt-2'］に記載して見たのですが、ブラウザで上手く表示されませんでした。
この場合は他の場所に別のコードを追記する必要がありましたか？
・メニューに「ログイン」を追加するというのは、【resources/views/commons/header.blade.php】に記載ということであっていましたか？
・ご指摘して頂いたコードを入力して見たのですが、コンフリクトの解消はされていますか？

ご確認よろしくお願いします。

2020-10-04 10:17 UTC, quest-academia commented on resources/views/auth/login.blade.php
> +                    {!! Form::submit('初めての方はこちらから', ['class' => 'btn btn-sm btn-info mt-2']) !!}
初めての方は〜のボタンが左側に寄っています。
こちらを修正ください！

<img width="260" alt="スクリーンショット 2020-10-04 8 23 13" src="https://user-images.githubusercontent.com/63336345/95012769-33ce5580-0676-11eb-8a55-30a65668ff0f.png">

2020-10-06 14:53 UTC, SekiYukihiro requested changes
ボタンの配置やサイズなどは良くなったと思います！

ただ、メニューのログインを押した場合に、
ログイン画面に遷移しないので、メニューのログインにリンクを貼りましょう！

2020-10-06 14:53 UTC, SekiYukihiro commented on resources/views/commons/header.blade.php
> +                <li class="nav-item"><a href="" class="nav-link white-text">ログイン</a></li>
こちらの内容だと、メニューのログインを押した場合に、
ログイン画面に遷移しないので、リンクを貼りましょう！

2020-10-08 05:46 UTC, kenji-0612 commented
お疲れ様です。

メニュー画面のログインボタンからログイン画面に遷移するように新たにリンクを追記しました。

・ユーザーズテーブルのマイグレーションファイルの作成
・マイグレーションファイルを実行して、マイグレーションが作成できているかの確認
の課題についてですが、

user_tableを作成し記述をしていったのですが、【php artisan migrate】コマンドを入力したところ
エラーの表示が出てしまっています。

・.envファイルの中身などは確認してみたのですが、特に異常は見られませんでした。
・ブラウザ上でのアプリの表示でも【商品一覧【商品検索】ボタンをクリックするとエラーが起きてしまっている状態です。

ご確認よろしくお願いします。

2020-10-08 15:35 UTC, kenji-0612 commented
お疲れ様です。

メニューのログインボタンをクリックして後にログイン画面に遷移するように変更しました。

ご確認よろしくお願いします。

2020-10-10 08:18 UTC, kenji-0612 commented
お疲れ様です。

users_tableの作成・マイグレーションを行いました。

ご確認よろしくお願いします。

2020-10-13 04:27 UTC, kenji-0612 commented
お疲れ様です。

新規登録画面の作成を行いました。

なるべく画面定義書に近い感じで作成して見ましたが、修正点やアドバイスなどがあればよろしくお願いします。

※定義書ではボタンの色が白になっていますが、他のボタン（ログイン画面や商品登録画面）の色がブルーだった為
統一した方がいいのかなと思い色を変えてあります。

ご確認よろしくお願いします。

2020-10-13 09:14 UTC, kenji-0612 commented
メニューボタンの遷移リンクと新規ユーザー登録機能の実装を行ってみたのですが、

ユーザー登録を行おうと登録ボタンをクリックするとエラーが表示されてしまいます。

詳しいエラーの内容はSlackに添付しておきますので、
ご確認よろしくお願いします。

2020-10-14 06:44 UTC, kenji-0612 commented
ブラウザで【ログイン画面】と【新規登録画面】の画面を狭めた時に発生する不具合についての変更を行いました。

※狭めた時に【初めての方はこちらから】ボタンも少し位置がズレてしまうのですが（通常の大きさで表示すると問題ないが、狭めると）、こちらも修正するべきでしょうか？

新規登録処理を行おうと登録ボタンをクリックするとエラーが出てしまいます。

パスワード部分のエラーでしょうか？

文字数に問題があるのかなと思いエラー番号などを調べてみたのですが、
自分では解決できなさそうだったのでご質問させて頂きました。

ご確認よろしくお願いします。

2020-10-17 18:27 UTC, kenji-0612 commented
お疲れ様です。

新規登録処理の実装と【初めての方はこちらから】のボタンの位置を修正しました。

・各項目の入力をし登録ボタンをクリックするとTOPページに遷移する内容になっているかと思います。
この流れで問題無いでしょうか？
・ボタンの位置が常に真ん中にくるように修正できたのですが、【メールアドレス】と【パスワード】を入力する欄が大きくなってしまいました。こちらももう少し定義書に近づけた方がよろしいでしょうか？

ご確認よろしくお願いします。

2020-10-17 21:46 UTC, SekiYukihiro commented on app/Http/Controllers/Auth/RegisterController.php
>       * Create a new controller instance.
４９行目以降の、
バリデーションの項目も、制限文字数などを書き換えましょう！

2020-10-17 21:53 UTC, SekiYukihiro commented on resources/views/auth/login.blade.php
> +@extends('layouts.app')
http://192.168.33.11/products/create

こちらの画面を参考に、バリデーションのエラーメッセージが
各入力フォームの下に表示されるように、やってみましょう！

2020-10-17 22:12 UTC, SekiYukihiro requested changes
おぉ、新規登録、きちんとできていますね！
素晴らしいです:blush:

では、ログイン画面と新規登録画面の見た目の修正ができたら、
次の段階に進みましょう！

各コメントをご確認下さい。

2020-10-17 22:12 UTC, SekiYukihiro commented on resources/views/auth/login.blade.php
> +    </div>
入力フォームが伸びてしまっているので、
新規登録画面と合わせて、伸びすぎないようにしましょう！

ボタンのサイズも、

・ログイン画面を新規登録画面に合わせる
・新規登録画面をログイン画面に合わせる

いずれかの対応をとりましょう。
<img width="1181" alt="スクリーンショット 2020-10-18 7 05 57" src="https://user-images.githubusercontent.com/45893677/96354375-fa372900-1110-11eb-9c7a-adc04133a053.png">

2020-10-19 14:15 UTC, kenji-0612 commented
・入力フォームのボタンの修正
・ボタンのサイズ変更（なるべくお互いのサイズが近いものにして見ました）
・バリデーション項目の文字制限数の書き換え

以上の３点を修正してみました。

ご確認よろしくお願いします。

2020-10-20 16:11 UTC, kenji-0612 commented
お疲れ様です。

・メールアドレスの最大文字数（６４文字）の変更
・エラーメッセージの作成

の２点を行いました。

いくつか分からない点があったのでご質問させて頂きます。

・４項目全て入力せずに登録ボタンをクリックすると【パスワード確認】の項目だけエラーメッセージが表示されません。
これは間違っていますか？それともこの場合は【パスワード】すら入力していないので【パスワード確認】には何も表示されなくても問題ないでしょうか？（パスワードを入力しパスワード確認で一致しない文字を入力すると確認用項目と一致していません。との記述は出ます）
・それぞれ各項目ごとのエラーメッセージを日本語（nameはユーザー名など）表記にした方が良いと思い
いろいろ試してみてはみたのですが、上手く変換されずに悩んでいます。

以上の２点とその他に足りない点などがあればアドバイスよろしくお願いします。

2020-10-21 07:09 UTC, kenji-0612 commented
エラーメッセージが日本語で表示されるようにファイルの書き換えを行いました。
（RegisterController.phpnの72行目以降も削除済み）

ご確認よろしくお願いします。

2020-10-23 02:30 UTC, kenji-0612 commented
お疲れ様です。

ログイン・ログアウト機能の実装を行いました。

・ログイン・ログアウト機能については特に大きな問題もなく実装できたかと思います。
・【初めての方はこちらから】のボタンをクリックすると【新規登録】画面に遷移するようにコードを書き換えようとすると
ボタンのデザインが崩れてしまいます。いろいろ試してみたのですが、デザインが反映されなかったり、上手く遷移しないなどの問題が起きてしまいます。
こういった場合はlink_to_route(signup'')とどのように組み合わせる？べきでしょうか？

ご確認よろしくお願いします。

2020-10-25 15:20 UTC, kenji-0612 commented
お疲れ様です。

Slackで指摘して頂いた３点についてになります。

・バリデーションメッセージを日本語表記に修正しようと実装してみようとしたのですが、なかなか上手く表示されません。
（この場合はどのファイルを修正していくのが正しいやり方でしょうか？）

・ログイン状態での画面遷移先について
http://192.168.33.11/loginにアクセスした時はホーム画面に遷移されるようになったのですが、
http://192.168.33.11/signupにアクセスしようとしたところエラー画面（高野さん作成の画面）やルートログインが定義されていませんとのエラーが表示されてしまいます。

・初めての方はこちらボタンの修正を行いました。
link_to_routeコマンドではなくhrefコマンドで遷移されるように記述してみました。
ボタンをクリックすると新規登録画面に遷移されるようにはなったのですが、この書き方であっっていたでしょうか？

提出が遅くなった上にほとんどが未完成になってしまい申し訳ありません。

以上の３点のご確認とアドバイスよろしくお願いします。

2020-10-27 07:01 UTC, kenji-0612 commented
・ログイン状態での画面遷移先の変更
・ルートが存在しないエラーと<a botton>部分の改善

を行いました。
現在は問題なくログイン画面も表示され【初めての方はこちらから】のボタンをクリックすると【新規登録】画面に遷移される状態になっています。
（途中でエラーに気付いたのですが、プッシュした後に書き直したので、エラーが出たままになっていました。すみませんでした。）

バリデーションメッセージについてなんですが、
せきさんにアドバイス頂いた通りauth.phpファイルの修正を行ってみたのですが、どうしてもエラーメッセージが日本語表記になりません。

・config / app.phpファイルの修正（'locale' => 'en',→'locale' => 'ja',）も行ってみたのですが改善されませんでした。

他のファイルも書き換えるべきでしょうか？

ご確認よろしくお願いします。

2020-10-27 16:22 UTC, kenji-0612 commented
エラーメッセージの【These credentials do not match our records.】部分を日本語で表示されるように
設定し直しました。

ご確認よろしくお願いします。

2020-10-27 22:01 UTC, SekiYukihiro commented on resources/views/auth/login.blade.php
> +            <a class="btn btn-info mt-3" href="http://192.168.33.11/signup">初めての方はこちらから</a>
hrefを使うのは全くOKなのですが、
`href="/signup"`

この書き方に訂正しましょう。

でないと、デプロイ した際のURLは
http://192.168.33.11/
ではないので、デプロイ した際にエラーが出てしまいます！

宜しくお願いします！

2020-10-27 22:05 UTC, SekiYukihiro commented
確認しました。
ほぼ完璧ですね。よくできていると思います😊

GitHubにコメントを書きましたが、
１点訂正をお願いしたい部分があります。

また、GitHubは実務でもよく使うので、
コメントの書き方に慣れて頂きたいという思いもあり、
今回から、GitHub上でレビューコメントを受けた場合、GitHub上でコメントを返しましょう！
（訂正しました、など簡単なレスでもOKです）

2020-10-27 22:05 UTC, SekiYukihiro requested changes
確認しました。
ほぼ完璧ですね。よくできていると思います😊

GitHubにコメントを書きましたが、
１点訂正をお願いしたい部分があります。

また、GitHubは実務でもよく使うので、
コメントの書き方に慣れて頂きたいという思いもあり、
今回から、GitHub上でレビューコメントを受けた場合、GitHub上でコメントを返しましょう！
（訂正しました、など簡単なレスでもOKです）

2020-10-28 05:53 UTC, kenji-0612 commented
お疲れ様です。

上記で指摘頂いた【href=】部分の修正を行いました。

ご確認よろしくお願いします。

2020-10-28 21:27 UTC, SekiYukihiro approved these changes
OKです！

確認させて頂いて、
問題ありませんので、マージさせて頂きました😊

引き続き作業を宜しくお願い致します😄

2020-10-28 21:28 UTC, merged